Add publish package workflow
yamatolab/current-calculations-for-proteins pull request #25
Opened 2022-01-05 10:35 UTC by flat35hd99

2022-01-05 10:42 UTC, yamato97 requested changes
Thanks Wataru, two minor changes needed. 

1) In docs/source/install.rst, LINE 35:
through GitLab repository => through GitHub repository
2) In README.rst
git clone https://gitlab.com/yamato97/current-calculations-for-proteins.git
=> 
git clone https://github.com/yamatolab/current-calculations-for-proteins.git

2022-01-05 10:52 UTC, flat35hd99 commented
@yamato97 Those issues has been resolved in #24 , [this commit](https://github.com/yamatolab/current-calculations-for-proteins/pull/24/commits/dc2b924f6aedc130ba22a672500dbac1f6d34e07). Other issues were also resolved in that pull request. This pull request is just to add a workflow to publish pypi package automatically.

2022-01-05 13:54 UTC, yamato97 approved these changes
Due to my ignorance, I am not fully understand the effect of this commit. As such, I trust Wataru's work on this.

2022-01-06 03:38 UTC, vantelindome approved these changes

2022-01-06 03:39 UTC, merged