Improved cal_tc.py for decomposing heat conductivity
yamatolab/current-calculations-for-proteins pull request #34
Opened 2023-05-01 06:05 UTC by shigure1223

I have changed the cal_tc.py so that the conductivity will be decomposed.
The data will be output with no problems, whenever decomp is set "no" in the config file.

2023-05-01 06:07 UTC, flat35hd99 commented
Thank you for your PR! I'll read your changes tonight(19:00-)


On Mon, May 1, 2023, 3:05 PM shigure1223 ***@***.***> wrote:

> I have changed the cal_tc.py so that the conductivity will be decomposed.
> The data will be output with no problems, whenever decomp is set "no" in
> the config file.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/yamatolab/current-calculations-for-proteins/pull/34
> Commit Summary
>
>    - b0bd129
>    <https://github.com/yamatolab/current-calculations-for-proteins/pull/34/commits/b0bd1290ea65183c49d79fcb578de18ccd054c26>
>    Improved cal_tc.py for decomposing heat conductivity
>
> File Changes
>
> (1 file
> <https://github.com/yamatolab/current-calculations-for-proteins/pull/34/files>
> )
>
>    - *M* curp/script/cal_tc.py
>    <https://github.com/yamatolab/current-calculations-for-proteins/pull/34/files#diff-2af34c9e5585ea2ccfd6db0f5eb0568ca52187a7cd01a675c16583219c04d85c>
>    (46)
>
> Patch Links:
>
>    -
>    https://github.com/yamatolab/current-calculations-for-proteins/pull/34.patch
>    -
>    https://github.com/yamatolab/current-calculations-for-proteins/pull/34.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yamatolab/current-calculations-for-proteins/pull/34>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJJAHJFGEI4BHKVBZQYWPH3XD5HBZANCNFSM6AAAAAAXROZESQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-05-01 10:48 UTC, flat35hd99 requested changes

2023-05-01 10:48 UTC, flat35hd99 commented on curp/script/cal_tc.py
> +
Remove this empty line. You don't need two lines to separate code blocks.

2023-05-01 10:52 UTC, flat35hd99 commented
I would like you to change single points that I mentioned above.

Additionaly, I request you to do:

- `The data will be output with no problems, whenever decomp is set "no" in the config file.` Share the config file and options that you specified(both of flux and conductivity calculations). I cannot understand your test situation.
- If you have not checked the energy flux & conductivity calculations, please perform that test.(this is called "regression test")

2023-05-02 01:25 UTC, shigure1223 commented
Thank you for the comments.
I deleted the empty line.

I will share the config file and options that I specified(both of flux and conductivity calculations) below.

1. config file
```python
[input]
format = amber
first_last_interval = 1 999999 1
#group_file = atomgroup.dat

[input_amber]
target = trajectory
topology_file = system.dry.prmtop
coordinate_format = netcdf
coordinate_file = md.crd.nc
velocity_format = netcdf
velocity_file = md.vel.nc

[curp]
potential = amber12SB
method = heat-flux

group_method = residue
#group_method = file
flux_grain = group
group_pair_file = gpair.dat

remove_trans =  yes
remove_rotate = yes

log_frequency = 1000

[output]
filename = flux.nc
format = netcdf
decomp = no

output_energy = no
```

2. job file
```python
curp compute flux.cfg > $output/flux.log

curp cal-tc \
    --frame-range 1 60000 1 --average-shift 2 \
    --dt 0.001 \
    -a $output/acf.nc \
    -o $output/conductivity.dat \
    $output/flux.nc > $output/conductivity.log
```

2023-05-09 07:40 UTC, shigure1223 commented
I finished the regression test of energy & heat conductivity calculations.

1. For decomp=no, both energy & heat conductivity calculations had no changes in the result with curp1.3.1
2. For decomp=yes heat conductivity calculations, the total conductivity in "conductivity.dat" was the same as the decomp=no heat conductivity calculations
3. For decomp=no energy calculations, the result had no changes but there were one problem that some conductivity was printed 'nan'  (because we cannot calculate the conductivity of bonded interaction term when residues are apart).This is a natural result but to output the data into a manageable form, I changed like below

https://github.com/yamatolab/current-calculations-for-proteins/pull/34/commits/8a0b2af3180d631b4b6cfd13979ce987123a7dde

If there are other things I have to check , please let me know.
Thank  you.

2023-05-10 01:59 UTC, shigure1223 commented
Yes correct!!!

2023-05-10 03:42 UTC, flat35hd99 approved these changes
LGTM and the regression test was performed by @shigure1223 . It is good to merge.

2023-05-10 03:46 UTC, flat35hd99 commented
@yamato97 This PR provides decompose conductivity into conductivity of each force item. @shigure1223 also check this change make no side effect.

Please check and if this is okay, approve this PR.

2023-05-10 05:10 UTC, yamato97 commented
LGTM too.

2023-05-10 05:11 UTC, yamato97 commented
LGTM too

2023-05-10 05:12 UTC, yamato97 approved these changes

2023-05-10 05:14 UTC, merged